export default function Landing({ onCreate, onJoin, onLeaderboard }) {
  return (
    <div>
      <div className="hero">
        <div>
          <div className="eyebrow mb-24">
            <span className="dot" />
            BRADBURY TESTNET · ON-CHAIN AI
          </div>
          <h1 className="hero-title">
            SPEED.<span className="accent">CLICK</span><br />
            <span className="struck">QUIZ</span> SHOW
          </h1>
          <p className="text-muted" style={{ fontSize: '1.05rem', maxWidth: 520, lineHeight: 1.5 }}>
            Multiplayer trivia where the questions are written by an AI, the speed is measured by the blockchain itself, and disputes go to a tribunal of validators. Click first. Click right. Earn XP.
          </p>

          <div className="cta-dual">
            <div className="cta-card">
              <span className="kicker">01 — HOST</span>
              <h3 className="mt-12">Create a room</h3>
              <p>Spin up a fresh game. AI-generated questions seeded the moment you start.</p>
              <button className="btn btn-primary btn-lg" style={{ width: '100%' }} onClick={onCreate}>
                NEW ROOM →
              </button>
            </div>
            <div className="cta-card">
              <span className="kicker">02 — PLAY</span>
              <h3 className="mt-12">Join a room</h3>
              <p>Drop a friend's room code in. Lobbies hold 2–10 players.</p>
              <button className="btn btn-magenta btn-lg" style={{ width: '100%' }} onClick={onJoin}>
                ENTER CODE →
              </button>
            </div>
          </div>

          <div className="hero-meta">
            <div className="stat">
              <span className="stat-num tabular">2,418</span>
              <span className="stat-label">Games played</span>
            </div>
            <div className="stat">
              <span className="stat-num tabular">14,902</span>
              <span className="stat-label">XP awarded</span>
            </div>
            <div className="stat">
              <span className="stat-num tabular">37</span>
              <span className="stat-label">Disputes ruled</span>
            </div>
          </div>
        </div>

        <div className="live-widget">
          <div className="live-widget-head">
            <h4>// HOW IT WORKS</h4>
          </div>
          <ol style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              ['01', 'Connect wallet', 'MetaMask on Bradbury testnet.'],
              ['02', 'Create or join', '2–10 players, 5–10 rounds.'],
              ['03', 'Host starts', 'AI writes questions on-chain.'],
              ['04', 'Click fast', 'Block order = your speed bonus.'],
              ['05', 'Collect XP', 'Pushed to the global leaderboard.'],
            ].map(([n, t, d]) => (
              <li key={n} style={{ display: 'grid', gridTemplateColumns: '36px 1fr', gap: 12, padding: '10px 0', borderBottom: '1px solid var(--line)' }}>
                <span className="mono text-accent" style={{ fontSize: '0.78rem', paddingTop: 2 }}>{n}</span>
                <div>
                  <div style={{ fontWeight: 600, fontSize: '0.92rem', marginBottom: 2 }}>{t}</div>
                  <div className="text-muted" style={{ fontSize: '0.8rem' }}>{d}</div>
                </div>
              </li>
            ))}
          </ol>
          <button className="btn btn-ghost btn-sm" style={{ width: '100%', marginTop: 14 }} onClick={onLeaderboard}>
            VIEW GLOBAL LEADERBOARD →
          </button>
        </div>
      </div>

      <div className="feat-strip">
        {[
          ['01', 'AI-WRITTEN ROUNDS', 'Every game gets a fresh batch of questions, generated by an LLM at game-start, validated on-chain.'],
          ['02', 'BLOCK-ORDER SPEED', 'The chain decides who clicked first. No timestamps to fake. 1st = 100, 2nd = 75, 3rd = 50…'],
          ['03', 'TRIBUNAL DISPUTES', 'Think the AI got it wrong? Open a dispute. Validators re-run an impartial arbiter via Optimistic Democracy.'],
          ['04', 'GLOBAL XP LADDER', 'Wins push to a chain-wide leaderboard. Cumulative, immutable, and very smug.'],
        ].map(([n, t, d]) => (
          <div key={n} className="feat">
            <div className="feat-num">{n} / 04</div>
            <div className="feat-title">{t}</div>
            <div className="feat-desc">{d}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        <div className="card">
          <span className="kicker">SCORING / XP</span>
          <h3 className="display display-md mt-12 mb-16">Speed beats certainty.</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {[['1ST', '+100 XP', 'var(--accent)'], ['2ND', '+75 XP', 'var(--paper)'], ['3RD', '+50 XP', 'var(--paper)'], ['4TH+', '+25 XP', 'var(--muted-2)'], ['WRONG', '0 XP', 'var(--accent-2)']].map(([pos, xp, color]) => (
              <div key={pos} className="row-between" style={{ padding: '10px 14px', border: '1px solid var(--line)', borderRadius: 8, background: 'var(--ink)' }}>
                <span className="mono" style={{ fontSize: '0.85rem', color: 'var(--muted-2)' }}>{pos}</span>
                <span className="display" style={{ fontSize: '1.1rem', color }}>{xp}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="card">
          <span className="kicker">FLOW / HOW IT WORKS</span>
          <h3 className="display display-md mt-12 mb-16">Five steps. Zero patience required.</h3>
          <ol style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 12 }}>
            {[['01','Connect your wallet','MetaMask on Bradbury testnet.'],['02','Create or join a room','2–10 players, 5–10 rounds, your call.'],['03','Host hits start','AI generates the question pack on-chain.'],['04','Click fast, click right','Block-order decides your speed bonus.'],['05','XP flushes to the ladder','Winners pushed to the global board.']].map(([n, t, d]) => (
              <li key={n} style={{ display: 'grid', gridTemplateColumns: '40px 1fr', gap: 14 }}>
                <span className="mono text-accent" style={{ fontSize: '0.8rem', paddingTop: 2 }}>{n}</span>
                <div>
                  <div className="display" style={{ fontSize: '1rem', marginBottom: 2 }}>{t}</div>
                  <div className="text-muted" style={{ fontSize: '0.83rem' }}>{d}</div>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </div>
    </div>
  )
}
