/* global React, Avatar, shortAddr, nick, MOCK_ADDRS, MOCK_QUESTIONS, MOCK_LEADERBOARD */
const { useState, useEffect, useRef, useMemo, useCallback } = React;

// ═══════════════════════════════════════════════════════════════════════
// LANDING
// ═══════════════════════════════════════════════════════════════════════
function Landing({ onCreate, onJoin, onLeaderboard, connected, address }) {
  return (
    <div>
      <div className="hero">
        <div>
          <div className="eyebrow mb-24">
            <span className="dot" />
            BRADBURY TESTNET · ON-CHAIN AI
          </div>
          <h1 className="hero-title">
            SPEED.<span className="accent">CLICK</span><br/>
            <span className="struck">QUIZ</span> SHOW
          </h1>
          <p className="text-muted" style={{ fontSize: '1.05rem', maxWidth: 520, lineHeight: 1.5 }}>
            Multiplayer trivia where the questions are written by an AI, the speed is measured by the blockchain itself, and disputes go to a tribunal of validators. Click first. Click right. Earn XP.
          </p>

          <div className="cta-dual">
            <div className="cta-card">
              <span className="kicker">01 — HOST</span>
              <h3 className="mt-12">Create a room</h3>
              <p>Spin up a fresh game. AI-generated questions seeded the moment you start.</p>
              <button className="btn btn-primary btn-lg" style={{ width: '100%' }} onClick={onCreate}>
                NEW ROOM →
              </button>
            </div>
            <div className="cta-card">
              <span className="kicker">02 — PLAY</span>
              <h3 className="mt-12">Join a room</h3>
              <p>Drop a friend's room code in. Lobbies hold 2–10 players.</p>
              <button className="btn btn-magenta btn-lg" style={{ width: '100%' }} onClick={onJoin}>
                ENTER CODE →
              </button>
            </div>
          </div>

          <div className="hero-meta">
            <div className="stat">
              <span className="stat-num tabular">2,418</span>
              <span className="stat-label">Games played</span>
            </div>
            <div className="stat">
              <span className="stat-num tabular">14,902</span>
              <span className="stat-label">XP awarded</span>
            </div>
            <div className="stat">
              <span className="stat-num tabular">37</span>
              <span className="stat-label">Disputes ruled</span>
            </div>
          </div>
        </div>

        <LiveWidget onJoinAny={onJoin} onLeaderboard={onLeaderboard} />
      </div>

      <div className="feat-strip">
        {[
          ['01', 'AI-WRITTEN ROUNDS', 'Every game gets a fresh batch of questions, generated by an LLM at game-start, validated on-chain.'],
          ['02', 'BLOCK-ORDER SPEED', 'The chain decides who clicked first. No timestamps to fake. 1st = 100, 2nd = 75, 3rd = 50…'],
          ['03', 'TRIBUNAL DISPUTES', 'Think the AI got it wrong? Open a dispute. Validators re-run an impartial arbiter via Optimistic Democracy.'],
          ['04', 'GLOBAL XP LADDER', 'Wins push to a chain-wide leaderboard. Cumulative, immutable, and very smug.'],
        ].map(([n, t, d]) => (
          <div key={n} className="feat">
            <div className="feat-num">{n} / 04</div>
            <div className="feat-title">{t}</div>
            <div className="feat-desc">{d}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        <ScoringCard />
        <HowItWorksCard />
      </div>
    </div>
  );
}

function LiveWidget({ onJoinAny, onLeaderboard }) {
  const rooms = [
    { code: 'GLITCH-NEON-42', players: 6, max: 8, status: 'IN ROUND 3' },
    { code: 'GENLAYER-BATTLE', players: 4, max: 10, status: 'WAITING' },
    { code: 'MEMES-ONLY-77', players: 8, max: 10, status: 'IN ROUND 7' },
  ];
  return (
    <div className="live-widget">
      <div className="live-widget-head">
        <h4>// LIVE ROOMS</h4>
        <span className="chip chip-accent"><span className="pulse" style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--accent)' }} /> 3 active</span>
      </div>
      {rooms.map((r) => (
        <div key={r.code} className="live-room-row" onClick={onJoinAny}>
          <div>
            <div className="name">{r.code}</div>
            <div className="meta">{r.status} · {r.players}/{r.max} players</div>
          </div>
          <span className="chip chip-amber">{r.players}/{r.max}</span>
          <span className="text-muted mono" style={{ fontSize: '1rem' }}>→</span>
        </div>
      ))}
      <button className="btn btn-ghost btn-sm" style={{ width: '100%', marginTop: 12 }} onClick={onLeaderboard}>
        VIEW GLOBAL LEADERBOARD →
      </button>
    </div>
  );
}

function ScoringCard() {
  const tiers = [
    ['1ST', '+100 XP', 'var(--accent)'],
    ['2ND', '+75 XP', 'var(--paper)'],
    ['3RD', '+50 XP', 'var(--paper)'],
    ['4TH+', '+25 XP', 'var(--muted-2)'],
    ['WRONG', '0 XP', 'var(--accent-2)'],
  ];
  return (
    <div className="card">
      <span className="kicker">SCORING / XP</span>
      <h3 className="display display-md mt-12 mb-16">Speed beats certainty.</h3>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {tiers.map(([pos, xp, color]) => (
          <div key={pos} className="row-between" style={{
            padding: '10px 14px',
            border: '1px solid var(--line)',
            borderRadius: 8,
            background: 'var(--ink)',
          }}>
            <span className="mono" style={{ fontSize: '0.85rem', color: 'var(--muted-2)' }}>{pos}</span>
            <span className="display" style={{ fontSize: '1.1rem', color }}>{xp}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function HowItWorksCard() {
  const steps = [
    ['01', 'Connect your wallet', 'MetaMask on Bradbury testnet. Read-only mode works without it.'],
    ['02', 'Create or join a room', '2–10 players, 5–10 rounds, your call.'],
    ['03', 'Host hits start', 'AI generates the question pack on-chain.'],
    ['04', 'Click fast, click right', 'Block-order decides your speed bonus.'],
    ['05', 'XP flushes to the ladder', 'Winners pushed to the global board.'],
  ];
  return (
    <div className="card">
      <span className="kicker">FLOW / HOW IT WORKS</span>
      <h3 className="display display-md mt-12 mb-16">Five steps. Zero patience required.</h3>
      <ol style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 12 }}>
        {steps.map(([n, t, d]) => (
          <li key={n} style={{ display: 'grid', gridTemplateColumns: '40px 1fr', gap: 14 }}>
            <span className="mono text-accent" style={{ fontSize: '0.8rem', paddingTop: 2 }}>{n}</span>
            <div>
              <div className="display" style={{ fontSize: '1rem', marginBottom: 2 }}>{t}</div>
              <div className="text-muted" style={{ fontSize: '0.83rem' }}>{d}</div>
            </div>
          </li>
        ))}
      </ol>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════
// CREATE ROOM
// ═══════════════════════════════════════════════════════════════════════
function CreateRoom({ onBack, onCreated, showToast }) {
  const [code, setCode] = useState(() => generateCode());
  const [players, setPlayers] = useState(6);
  const [rounds, setRounds] = useState(8);
  const [busy, setBusy] = useState(false);

  function generateCode() {
    const a = ['NEON','GLITCH','PULSE','VORTEX','CIPHER','PHOTON','VOLT','ECHO','NYX'];
    const b = ['ORBIT','BATTLE','RIOT','SYNC','PIXEL','FROST','SPARK','RUSH'];
    return a[Math.floor(Math.random()*a.length)] + '-' + b[Math.floor(Math.random()*b.length)] + '-' + Math.floor(Math.random()*99).toString().padStart(2,'0');
  }

  async function handleCreate() {
    setBusy(true);
    await new Promise(r => setTimeout(r, 900));
    showToast('Room created on-chain ✓');
    onCreated({ code, players, rounds });
    setBusy(false);
  }

  return (
    <div style={{ maxWidth: 640, margin: '0 auto' }}>
      <button className="btn btn-ghost btn-sm mb-24" onClick={onBack}>← BACK</button>
      <span className="kicker">/ NEW ROOM</span>
      <h1 className="display display-lg mt-12 mb-24">Spin up a game.</h1>

      <div className="card">
        <div className="field mb-16">
          <label className="field-label">Room code</label>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 8 }}>
            <input
              className="input input-big"
              value={code}
              onChange={e => setCode(e.target.value.toUpperCase().replace(/\s/g,'-'))}
            />
            <button className="btn btn-ghost" onClick={() => setCode(generateCode())}>↻ ROLL</button>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <div className="field">
            <label className="field-label">Max players · 2–10</label>
            <Stepper value={players} setValue={setPlayers} min={2} max={10} />
          </div>
          <div className="field">
            <label className="field-label">Rounds · 5–10</label>
            <Stepper value={rounds} setValue={setRounds} min={5} max={10} />
          </div>
        </div>

        <div style={{ marginTop: 24, padding: 16, border: '1px dashed var(--line-2)', borderRadius: 10, background: 'var(--ink)' }}>
          <div className="kicker mb-12">/ TRANSACTION PREVIEW</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '6px 16px', fontSize: '0.82rem' }}>
            <span className="text-muted mono">METHOD</span>  <span className="mono">create_room</span>
            <span className="text-muted mono">CHAIN</span>   <span className="mono">Bradbury · 4221</span>
            <span className="text-muted mono">EST. GAS</span><span className="mono">~0.0008 GEN</span>
            <span className="text-muted mono">ARGS</span>    <span className="mono">"{code}", {players}, {rounds}</span>
          </div>
        </div>

        <button
          className="btn btn-primary btn-lg"
          style={{ width: '100%', marginTop: 18 }}
          disabled={busy || !code.trim()}
          onClick={handleCreate}
        >
          {busy ? <><span className="spinner" /> SIGNING…</> : 'CREATE ROOM ↗'}
        </button>
      </div>
    </div>
  );
}

function Stepper({ value, setValue, min, max }) {
  return (
    <div className="stepper">
      <button onClick={() => setValue(Math.max(min, value - 1))}>−</button>
      <span className="stepper-val">{value}</span>
      <button onClick={() => setValue(Math.min(max, value + 1))}>+</button>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════
// JOIN ROOM
// ═══════════════════════════════════════════════════════════════════════
function JoinRoom({ onBack, onJoined, showToast }) {
  const [code, setCode] = useState('');
  const [busy, setBusy] = useState(false);

  async function handleJoin() {
    if (!code.trim()) return;
    setBusy(true);
    await new Promise(r => setTimeout(r, 800));
    showToast('Joined room ✓');
    onJoined({ code: code.toUpperCase() });
    setBusy(false);
  }

  return (
    <div style={{ maxWidth: 560, margin: '0 auto' }}>
      <button className="btn btn-ghost btn-sm mb-24" onClick={onBack}>← BACK</button>
      <span className="kicker">/ JOIN A GAME</span>
      <h1 className="display display-lg mt-12 mb-24">Drop the code.</h1>

      <div className="card">
        <div className="field mb-16">
          <label className="field-label">Room code</label>
          <input
            autoFocus
            className="input input-big"
            placeholder="GLITCH-NEON-42"
            value={code}
            onChange={e => setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,''))}
          />
        </div>
        <button
          className="btn btn-magenta btn-lg"
          style={{ width: '100%' }}
          disabled={busy || !code.trim()}
          onClick={handleJoin}
        >
          {busy ? <><span className="spinner" /> JOINING…</> : 'JOIN ROOM →'}
        </button>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════
// LOBBY
// ═══════════════════════════════════════════════════════════════════════
function Lobby({ room, isHost, myAddress, onStart, onLeave, showToast }) {
  const [players, setPlayers] = useState(() => {
    // start with host (me) + 2 mock joiners
    return [
      myAddress || MOCK_ADDRS[0],
      MOCK_ADDRS[1],
      MOCK_ADDRS[2],
    ];
  });
  const [busy, setBusy] = useState(false);

  // Simulate players joining
  useEffect(() => {
    const id = setTimeout(() => {
      if (players.length < Math.min(5, room.players)) {
        setPlayers(p => [...p, MOCK_ADDRS[(p.length) % MOCK_ADDRS.length]]);
      }
    }, 4500);
    return () => clearTimeout(id);
  }, [players, room.players]);

  async function handleStart() {
    setBusy(true);
    showToast('AI generating questions on-chain…');
    await new Promise(r => setTimeout(r, 1500));
    onStart();
    setBusy(false);
  }

  const inviteUrl = `speed.click/r/${room.code}`;

  return (
    <div>
      <button className="btn btn-ghost btn-sm mb-24" onClick={onLeave}>← LEAVE</button>

      <div className="lobby-grid">
        <div className="room-code-card">
          <div className="row-between" style={{ position: 'relative' }}>
            <span className="kicker">/ ROOM CODE</span>
            <span className="chip chip-amber">
              <span className="pulse" style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--amber)' }} />
              WAITING
            </span>
          </div>
          <div className="room-code-display">{room.code}</div>

          <div className="invite-bar">
            <span className="url">{inviteUrl}</span>
            <button className="btn btn-sm btn-ghost" onClick={() => { navigator.clipboard?.writeText(inviteUrl); showToast('Invite link copied'); }}>
              ⧉ COPY
            </button>
          </div>

          <div className="row gap-16 mt-24" style={{ flexWrap: 'wrap' }}>
            <span className="chip">⏱ {room.rounds} rounds</span>
            <span className="chip">⌬ {players.length}/{room.players} joined</span>
            <span className="chip chip-accent">⚡ AI on Bradbury</span>
          </div>

          {isHost ? (
            <button
              className="btn btn-primary btn-lg mt-24"
              style={{ width: '100%' }}
              onClick={handleStart}
              disabled={busy || players.length < 2}
            >
              {busy
                ? <><span className="spinner" /> GENERATING QUESTIONS…</>
                : players.length < 2
                  ? `WAITING FOR PLAYERS · ${players.length}/2 MIN`
                  : `START GAME · ${players.length} PLAYERS ⚡`}
            </button>
          ) : (
            <div className="mt-24 center text-muted" style={{ fontSize: '0.85rem' }}>
              <span className="spinner" /> Waiting for host to start the game…
            </div>
          )}
        </div>

        <div className="card">
          <div className="row-between mb-16">
            <span className="kicker">/ PLAYERS</span>
            <span className="mono text-muted" style={{ fontSize: '0.78rem' }}>{players.length}/{room.players}</span>
          </div>
          <div className="col gap-8">
            {Array.from({ length: room.players }).map((_, i) => {
              const addr = players[i];
              if (!addr) {
                return (
                  <div key={i} className="player-slot empty">
                    <span className="text-muted mono center" style={{ fontSize: '1rem' }}>—</span>
                    <span className="text-muted mono">empty slot</span>
                    <span className="mono" style={{ fontSize: '0.7rem', color: 'var(--muted)' }}>idle</span>
                  </div>
                );
              }
              const me = addr === myAddress;
              const host = i === 0;
              return (
                <div key={addr+i} className={`player-slot${me ? ' me' : ''}${host ? ' host' : ''} anim-up`}>
                  <Avatar addr={addr} name={nick(addr)} />
                  <div>
                    <div className="name">{nick(addr)}{me ? ' · YOU' : ''}</div>
                    <div className="addr">{shortAddr(addr)}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { Landing, CreateRoom, JoinRoom, Lobby });
